# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-03-16 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Completed'),
        ),
    ]
