# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-03-17 19:39
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_register_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number must be entered 9 Up to 20 digits', regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone Number'),
        ),
    ]
