# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-04-06 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0008_register_is_coming'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Active'),
        ),
    ]
