# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-01 09:52
from __future__ import unicode_literals

import activity.models
from django.db import migrations, models
import django.db.models.deletion
import geoposition.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('speaker', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('year', models.PositiveSmallIntegerField(unique=True, verbose_name='Year')),
                ('is_active', models.BooleanField(verbose_name='Active')),
                ('meta_tags', models.TextField(blank=True, null=True, verbose_name='Meta Tags')),
                ('logo', models.TextField(blank=True, null=True, verbose_name='Logo')),
                ('short_description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Short Description')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('register_url', models.URLField(blank=True, null=True, verbose_name='Register URL')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('transportation', models.TextField(blank=True, null=True, verbose_name='Transportation')),
                ('accommodation', models.TextField(blank=True, null=True, verbose_name='Accommodation')),
                ('speakers', models.ManyToManyField(blank=True, to='speaker.Speaker', verbose_name='Speakers')),
            ],
            options={
                'verbose_name': 'Activity',
                'ordering': ('-year',),
                'verbose_name_plural': 'Activities',
            },
        ),
        migrations.CreateModel(
            name='ActivityDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('document', models.FileField(upload_to=activity.models.set_activity_documents_upload_path, verbose_name='Document')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_documents', to='activity.Activity', verbose_name='Activity')),
            ],
            options={
                'verbose_name': 'Activity Document',
                'verbose_name_plural': 'Activity Documents',
            },
        ),
        migrations.CreateModel(
            name='ActivityMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('description', models.CharField(blank=True, max_length=250, null=True, verbose_name='Description')),
                ('coordinates', geoposition.fields.GeopositionField(max_length=42, verbose_name='Coordinates')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.Activity', verbose_name='Activity')),
            ],
            options={
                'verbose_name': 'Activity Map',
                'ordering': ('activity',),
                'verbose_name_plural': 'Activity Maps',
            },
        ),
        migrations.CreateModel(
            name='ActivitySocialAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('url', models.URLField(verbose_name='URL')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.SocialAccount', verbose_name='Account')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.Activity', verbose_name='Activity')),
            ],
            options={
                'ordering': ('activity',),
                'verbose_name': 'Activity Social Account',
                'verbose_name_plural': 'Activity Social Accounts',
            },
        ),
        migrations.AlterUniqueTogether(
            name='activitysocialaccount',
            unique_together=set([('activity', 'account')]),
        ),
    ]
