# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-27 16:06
from __future__ import unicode_literals

import activity.models
from django.db import migrations, models
import django.db.models.deletion
import geoposition.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Year')),
                ('logo', models.TextField(blank=True, null=True, verbose_name='Logo')),
                ('meta_tags', models.TextField(blank=True, null=True, verbose_name='Meta Tags')),
                ('short_description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Short Description')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('register_url', models.URLField(blank=True, null=True, verbose_name='Register URL')),
            ],
            options={
                'verbose_name_plural': 'Activities',
                'ordering': ('-year',),
                'verbose_name': 'Activity',
            },
        ),
        migrations.CreateModel(
            name='ActivityDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to=activity.models.set_activity_upload_path, verbose_name='Document')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_documents', to='activity.Activity', verbose_name='Activity')),
            ],
            options={
                'verbose_name_plural': 'Activity Documents',
                'verbose_name': 'Activity Document',
            },
        ),
        migrations.CreateModel(
            name='ActivityMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=250, null=True, verbose_name='Description')),
                ('coordinates', geoposition.fields.GeopositionField(max_length=42, verbose_name='Coordinates')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.Activity', verbose_name='Activity')),
            ],
            options={
                'verbose_name_plural': 'Activity Maps',
                'ordering': ('activity',),
                'verbose_name': 'Activity Map',
            },
        ),
    ]
