# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-03-16 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0012_activity_has_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='contact_info',
            field=models.TextField(blank=True, null=True, verbose_name='Contact Information'),
        ),
        migrations.AddField(
            model_name='activity',
            name='register_info',
            field=models.TextField(blank=True, null=True, verbose_name='Register Information'),
        ),
    ]
