# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-03-22 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0013_auto_20180316_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='has_speaker_company',
            field=models.BooleanField(default=False, verbose_name='Speaker Company'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='has_activity_document',
            field=models.BooleanField(default=False, verbose_name='Activity Document'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='has_register_url',
            field=models.BooleanField(default=False, verbose_name='Register URL'),
        ),
    ]
