# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-05-03 17:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import hackathon.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activity', '0009_auto_20170425_1903'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hackathon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('register_url', models.URLField(blank=True, null=True, verbose_name='Register URL')),
                ('has_register_url', models.BooleanField(default=True, verbose_name='Register URL')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to=hackathon.models.set_activity_hackathon_upload_path, verbose_name='Main Image')),
                ('is_active', models.BooleanField(verbose_name='Active')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.Activity', verbose_name='Activity')),
            ],
            options={
                'verbose_name_plural': 'Hackathons',
                'ordering': ('activity',),
                'verbose_name': 'Hackathon',
            },
        ),
        migrations.CreateModel(
            name='HackathonPrize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to=hackathon.models.set_activity_hackathon_prize_upload_path, verbose_name='Main Image')),
                ('is_active', models.BooleanField(verbose_name='Active')),
                ('order_id', models.PositiveSmallIntegerField(db_index=True, default=0, editable=False)),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hackathon.Hackathon', verbose_name='Hackathon')),
            ],
            options={
                'verbose_name_plural': 'Hackathon Prizes',
                'ordering': ('order_id',),
                'verbose_name': 'Hackathon Prize',
            },
        ),
    ]
