# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-05-07 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='has_comment',
            field=models.BooleanField(default=False, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='main_image_height',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Main Image Height'),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='main_image_width',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Main Image Width'),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='team_description',
            field=models.TextField(blank=True, null=True, verbose_name='Team Description'),
        ),
        migrations.AddField(
            model_name='hackathonprize',
            name='main_image_height',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Main Image Height'),
        ),
        migrations.AddField(
            model_name='hackathonprize',
            name='main_image_width',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Main Image Width'),
        ),
    ]
