# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-01 09:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import speaker.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('image', models.ImageField(blank=True, null=True, upload_to=speaker.models.set_speaker_image_upload_path, verbose_name='Image')),
            ],
            options={
                'ordering': ('first_name', 'last_name'),
                'verbose_name': 'Speaker',
                'verbose_name_plural': 'Speakers',
            },
        ),
        migrations.CreateModel(
            name='SpeakerSocialAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('url', models.URLField(verbose_name='URL')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.SocialAccount', verbose_name='Account')),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speaker.Speaker', verbose_name='Speaker')),
            ],
            options={
                'ordering': ('speaker',),
                'verbose_name': 'Speaker Social Account',
                'verbose_name_plural': 'Speaker Social Accounts',
            },
        ),
        migrations.AlterUniqueTogether(
            name='speaker',
            unique_together=set([('first_name', 'last_name')]),
        ),
        migrations.AlterUniqueTogether(
            name='speakersocialaccount',
            unique_together=set([('speaker', 'account')]),
        ),
    ]
