# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-06 08:08
from __future__ import unicode_literals

import adminsortable.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('speaker', '0003_speakersocialaccount_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='speakersocialaccount',
            options={'ordering': ('order_id', 'account'), 'verbose_name': 'Speaker Social Account', 'verbose_name_plural': 'Speaker Social Accounts'},
        ),
        migrations.AlterField(
            model_name='speakersocialaccount',
            name='account',
            field=adminsortable.fields.SortableForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.SocialAccount', verbose_name='Account'),
        ),
    ]
