# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-27 13:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('speaker', '0005_auto_20170320_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeakerApplicationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name_plural': 'Speaker Application Types',
                'verbose_name': 'Speaker Application Type',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='speakerapplication',
            name='other_social_account',
            field=models.URLField(blank=True, null=True, verbose_name='Other Social Account'),
        ),
        migrations.AddField(
            model_name='speakerapplication',
            name='application_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='speaker.SpeakerApplicationType', verbose_name='Application Type'),
        ),
        migrations.AlterUniqueTogether(
            name='speakerapplication',
            unique_together=set([('activity', 'application_type', 'first_name', 'last_name')]),
        ),
    ]
