# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-06 08:05
from __future__ import unicode_literals

from django.db import migrations, models
import sponsor.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=sponsor.models.set_sponsor_logo_upload_path, verbose_name='Logo')),
            ],
            options={
                'ordering': ('name',),
                'verbose_name': 'Sponsor',
                'verbose_name_plural': 'Sponsors',
            },
        ),
        migrations.CreateModel(
            name='SponsorType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('order_id', models.PositiveSmallIntegerField(db_index=True, default=0, editable=False)),
            ],
            options={
                'ordering': ('order_id', 'name'),
                'verbose_name': 'Sponsor Type',
                'verbose_name_plural': 'Sponsor Types',
            },
        ),
    ]
