# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-08 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='logo_height',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Logo Height'),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='logo_width',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Logo Width'),
        ),
    ]
