# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-09 08:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0002_auto_20170308_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsor',
            name='logo_height',
        ),
        migrations.RemoveField(
            model_name='sponsor',
            name='logo_width',
        ),
    ]
