# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-03-21 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_register_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='tshirt_size',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'S'), (2, 'M'), (3, 'L'), (4, 'XL'), (5, 'XXL')], null=True, verbose_name='T-shirt Size'),
        ),
        migrations.AlterField(
            model_name='register',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Active'),
        ),
    ]
