# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-03-30 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0005_auto_20180321_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='tshirt_size',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'XS'), (1, 'S'), (2, 'M'), (3, 'L'), (4, 'XL'), (5, 'XXL')], null=True, verbose_name='T-shirt Size'),
        ),
    ]
