# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-13 05:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import gallery.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activity', '0008_auto_20170323_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('tag', models.CharField(max_length=100, verbose_name='Tag')),
                ('url', models.URLField(blank=True, max_length=1000, null=True, verbose_name='URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('order_id', models.PositiveSmallIntegerField(db_index=True, default=0, editable=False)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.Activity', verbose_name='Activity')),
            ],
            options={
                'ordering': ('order_id', 'activity', 'name'),
                'verbose_name': 'Gallery',
                'verbose_name_plural': 'Galleries',
            },
        ),
        migrations.CreateModel(
            name='GalleryContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('image', models.ImageField(upload_to=gallery.models.set_gallerycontent_images_upload_path, verbose_name='Image')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('order_id', models.PositiveSmallIntegerField(db_index=True, default=0, editable=False)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.Gallery', verbose_name='Gallery')),
            ],
            options={
                'ordering': ('order_id', 'gallery'),
                'verbose_name': 'Gallery Content',
                'verbose_name_plural': 'Gallery Contents',
            },
        ),
    ]
