# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-05-07 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0002_auto_20170507_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='has_description',
            field=models.BooleanField(default=False, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='has_prize',
            field=models.BooleanField(default=False, verbose_name='Prize'),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='has_team_description',
            field=models.BooleanField(default=False, verbose_name='Team Description'),
        ),
    ]
