# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-01 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speaker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='speaker',
            options={'ordering': ('order_id', 'first_name', 'last_name'), 'verbose_name': 'Speaker', 'verbose_name_plural': 'Speakers'},
        ),
        migrations.AlterModelOptions(
            name='speakersocialaccount',
            options={'ordering': ('order_id',), 'verbose_name': 'Speaker Social Account', 'verbose_name_plural': 'Speaker Social Accounts'},
        ),
        migrations.AddField(
            model_name='speaker',
            name='order_id',
            field=models.PositiveSmallIntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AddField(
            model_name='speakersocialaccount',
            name='order_id',
            field=models.PositiveSmallIntegerField(db_index=True, default=0, editable=False),
        ),
    ]
