# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-20 13:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import speaker.models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0007_activity_has_speaker_application'),
        ('speaker', '0004_auto_20170306_1008'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeakerApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('image', models.ImageField(blank=True, null=True, upload_to=speaker.models.set_speaker_image_upload_path, verbose_name='Image')),
                ('company', models.CharField(blank=True, max_length=255, null=True, verbose_name='Company')),
                ('position', models.CharField(blank=True, max_length=255, null=True, verbose_name='Position')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='Twitter')),
                ('github', models.URLField(blank=True, null=True, verbose_name='Github')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='Linkedin')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.Activity', verbose_name='Activity')),
            ],
            options={
                'verbose_name': 'Speaker Application',
                'ordering': ('activity', 'first_name', 'last_name'),
                'verbose_name_plural': 'Speaker Applications',
            },
        ),
        migrations.AddField(
            model_name='speaker',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='speaker',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='speaker',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='speakersocialaccount',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.SocialAccount', verbose_name='Account'),
        ),
        migrations.AlterUniqueTogether(
            name='speakerapplication',
            unique_together=set([('activity', 'first_name', 'last_name')]),
        ),
    ]
