# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-03-22 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speaker', '0006_auto_20170327_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='company_url',
            field=models.URLField(blank=True, null=True, verbose_name='Company URL'),
        ),
        migrations.AddField(
            model_name='speakerapplication',
            name='company_url',
            field=models.URLField(blank=True, null=True, verbose_name='Company URL'),
        ),
    ]
