# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2019-03-23 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speaker', '0007_auto_20180322_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='Bio'),
        ),
        migrations.AddField(
            model_name='speakerapplication',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='Bio'),
        ),
    ]
