# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-01 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitysocialaccount',
            options={'ordering': ('order_id', 'activity'), 'verbose_name': 'Activity Social Account', 'verbose_name_plural': 'Activity Social Accounts'},
        ),
        migrations.AddField(
            model_name='activitysocialaccount',
            name='order_id',
            field=models.PositiveSmallIntegerField(db_index=True, default=0, editable=False),
        ),
    ]
