# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-06 08:05
from __future__ import unicode_literals

import adminsortable.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0001_initial'),
        ('activity', '0003_auto_20170302_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivitySponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('order_id', models.PositiveSmallIntegerField(db_index=True, default=0, editable=False)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.Activity', verbose_name='Activity')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sponsor.Sponsor', verbose_name='Sponsor')),
                ('sponsor_type', adminsortable.fields.SortableForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sponsor.SponsorType', verbose_name='Sponsor Type')),
            ],
            options={
                'ordering': ('order_id', 'sponsor_type'),
                'verbose_name': 'Activity Sponsor',
                'verbose_name_plural': 'Activity Sponsors',
            },
        ),
        migrations.AlterUniqueTogether(
            name='activitysponsor',
            unique_together=set([('activity', 'sponsor')]),
        ),
    ]
