# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-09 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0005_activity_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitysponsor',
            name='logo_height',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Logo Height'),
        ),
        migrations.AddField(
            model_name='activitysponsor',
            name='logo_width',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Logo Width'),
        ),
    ]
