# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-16 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0006_auto_20170309_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='has_speaker_application',
            field=models.BooleanField(default=False, verbose_name='Speaker Application'),
        ),
    ]
