# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-25 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0008_auto_20170323_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='hackathon_register_url',
            field=models.URLField(blank=True, null=True, verbose_name='Hackathon Register URL'),
        ),
        migrations.AddField(
            model_name='activity',
            name='has_hackathon_register_url',
            field=models.BooleanField(default=True, verbose_name='Hackathon Register URL'),
        ),
    ]
