# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-05-03 18:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0009_auto_20170425_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='hackathon_register_url',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='has_hackathon_register_url',
        ),
    ]
