# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-05-07 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0010_auto_20170503_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='has_comment',
            field=models.BooleanField(default=False, verbose_name='Comment'),
        ),
    ]
