# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2019-03-18 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0014_auto_20180322_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='history_note',
            field=models.TextField(blank=True, null=True, verbose_name='History Note'),
        ),
    ]
