# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2019-03-25 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0015_activity_history_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityTweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('text', models.TextField(verbose_name='Text')),
                ('username', models.CharField(max_length=250, verbose_name='Username')),
                ('user_screenname', models.CharField(max_length=250, verbose_name='Fullname')),
                ('tweet_create_date', models.DateTimeField(verbose_name='Create Date')),
                ('user_id', models.PositiveSmallIntegerField(unique=True, verbose_name='userid')),
                ('user_avatar', models.FileField(upload_to='', verbose_name='User Avatar')),
                ('order_id', models.PositiveSmallIntegerField(db_index=True, default=0, editable=False)),
            ],
            options={
                'verbose_name': 'Activity Tweet',
                'verbose_name_plural': 'Activity Tweets',
                'ordering': ('order_id',),
            },
        ),
    ]
