# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2019-03-27 10:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0016_activitytweet'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitytweet',
            name='activity',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='activity.Activity', verbose_name='Activity'),
            preserve_default=False,
        ),
    ]
