# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-02 13:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activity', '0003_auto_20170302_1537'),
        ('speaker', '0002_auto_20170301_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('date', models.DateField(verbose_name='Date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.Activity', verbose_name='Activity')),
            ],
            options={
                'ordering': ('activity', 'date'),
                'verbose_name': 'Program',
                'verbose_name_plural': 'Programs',
            },
        ),
        migrations.CreateModel(
            name='ProgramContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('subject', models.CharField(blank=True, max_length=255, null=True, verbose_name='Subject')),
                ('annotation', models.CharField(blank=True, max_length=255, null=True, verbose_name='Annotation')),
                ('start_time', models.TimeField(verbose_name='Start Time')),
                ('end_time', models.TimeField(verbose_name='End Time')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.Program', verbose_name='Program')),
                ('speaker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='speaker.Speaker', verbose_name='Speaker')),
            ],
            options={
                'ordering': ('program', 'start_time'),
                'verbose_name': 'Program Content',
                'verbose_name_plural': 'Program Contents',
            },
        ),
    ]
