# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-10 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speaker', '0004_auto_20170306_1008'),
        ('program', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programcontent',
            name='speaker',
        ),
        migrations.AddField(
            model_name='programcontent',
            name='speakers',
            field=models.ManyToManyField(blank=True, to='speaker.Speaker', verbose_name='Speaker'),
        ),
        migrations.AlterField(
            model_name='programcontent',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='End Time'),
        ),
    ]
