# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-27 09:12
from __future__ import unicode_literals

from django.db import migrations, models
import program.models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0002_auto_20170310_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='programcontent',
            name='presentation_document',
            field=models.FileField(blank=True, null=True, upload_to=program.models.set_programcontent_documents_upload_path, verbose_name='Presentation Document'),
        ),
        migrations.AddField(
            model_name='programcontent',
            name='presentation_url',
            field=models.URLField(blank=True, null=True, verbose_name='Presentation URL'),
        ),
    ]
