# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2019-03-09 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0003_auto_20170327_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='description',
            field=models.CharField(blank=True, max_length=256, verbose_name='Description'),
        ),
    ]
