# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2019-03-18 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0004_program_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
    ]
