# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2019-03-23 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0005_auto_20190318_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title'),
        ),
    ]
