# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2019-03-27 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0006_program_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='icon',
            field=models.CharField(choices=[('party', 'Eğlence'), ('story', 'Hikaye'), ('technical', 'teknik')], default='party', max_length=20, verbose_name='Title'),
            preserve_default=False,
        ),
    ]
